name: Auto Commit Changes

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Auto Commit Action
        uses: your-github-username/auto-commit-action@main
        with:
          github_token: ${{ secrets.GH_PAT }}
