name: Hourly Format and Auto Commit

on:
  schedule:
    - cron: "0 * * * *" # Every hour
  workflow_dispatch: # So you can run it manually from the Actions tab

jobs:
  format-and-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (for Prettier or similar tools)
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Prettier
        run: npm install --global prettier

      - name: Format code
        run: prettier --write .

      - name: Auto commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-format code (hourly)"
